apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config-prod
  namespace: voting-app-dev
data:
  FLASK_ENV: production
  DATABASE_PATH: postgresql://postgres:postgres@db:5432/voting_db
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  POSTGRES_DB: voting_db
  POSTGRES_USER: postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: '5432'
stringData:
  SECRET_KEY: change-me-to-a-strong-random-key-min-32-chars
  POSTGRES_PASSWORD: change-me-to-a-strong-password
  DOCKER_REGISTRY_PASSWORD: your-docker-hub-token