apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: denish952/voting-app-result:39
        ports:
        - containerPort: 80
        
        envFrom:
        - configMapRef:
            name: voting-config-prod
        - secretRef:
            name: voting-secrets-prod
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: voting-app-dev
spec:
  selector:
    app: result
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
