apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: denish952/voting-app-worker:39
        
        envFrom:
        - configMapRef:
            name: voting-config-prod
        - secretRef:
            name: voting-secrets-prod
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
